server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/milidb
    username: mili
    password: admin123
    hikari:
      maximum-pool-size: 10
      connection-timeout: 2000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    br.com.mili.backend: DEBUG

app:
  jwt:
    secret: ${JWT_SECRET:070bf38968c95f41ec7c1760b1cd46f5929f26e3e61bce4ecfa3230b4ac578c7}
    expiration: 3600
    cookie-name: access_token
    cookie-domain: localhost
    cookie-secure: false         # Mantém como 'false' para desenvolvimento em HTTP
    cookie-samesite: Lax        # DE 'Lax' PARA 'None'
