spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/milidb
    username: mili
    password: admin123
    hikari:
      maximum-pool-size: 10
      connection-timeout: 2000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
logging:
  level:
    br.com.mili.backend: DEBUG
